// DO NOT EDIT, generated by goctl
package types

type CaptchaReq struct {
}

type CaptchaResp struct {
	CaptchaId string `json:"captchaId"`
	PicPath   string `json:"picPath"`
}

type UserLoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type UserLoginResp struct {
	Username string `json:"username"`
	NickName string `json:"nickName"`
	Token    string `json:"token"`
}

type UserRegistryReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type UserRegistryResp struct {
	Username string `json:"username"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
}
