// DO NOT EDIT, generated by goctl
package types

type CaptchaReq struct {
}

type CaptchaResp struct {
	CaptchaId string `json:"captchaId"`
	PicPath   string `json:"picPath"`
}

type GetUserInfoReq struct {
	Username string `json:"username"`
}

type GetUserInfoResp struct {
	NickName string `json:"nickName"`
	Email    string `json:"email"`
}

type JwtTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdataSecertReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type UpdataSecertResp struct {
	Username string `json:"username"`
	JwtTokenResp
}

type UserDeleteReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserDeleteResp struct {
	Info string `json:"info"`
}

type UserLoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type UserLoginResp struct {
	Username string `json:"username"`
	NickName string `json:"nickName"`
	Token    string `json:"token"`
	JwtTokenResp
}

type UserRegistryReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type UserRegistryResp struct {
	Username string `json:"username"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
}
