// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	"EBook/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/registry",
			Handler: userRegistryHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/login",
			Handler: userLoginHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/captch",
			Handler: userCaptchHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/delete",
			Handler: userDeleteHandler(serverCtx),
		},
	})
}
