// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	"EBook/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/registry",
			Handler: userRegistryHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/login",
			Handler: userLoginHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/captcha",
			Handler: userCaptchHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/delete",
			Handler: userDeleteHandler(serverCtx),
		},
	})

	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/user/info",
			Handler: getUserInfoHandler(serverCtx),
		},
		{
			Method:  http.MethodPut,
			Path:    "/updatasecert",
			Handler: updataUserSecertHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/upload/book",
			Handler: uploadBookHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/download/book",
			Handler: downloadBookHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/book/count",
			Handler: getBookByCountHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/book/page",
			Handler: getBookByPageHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/book/totalc",
			Handler: getBookTotalCHandler(serverCtx),
		},
	})
}
