// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/www.proto

package www

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Www service

type WwwService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Www_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Www_PingPongService, error)
}

type wwwService struct {
	c    client.Client
	name string
}

func NewWwwService(name string, c client.Client) WwwService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "www"
	}
	return &wwwService{
		c:    c,
		name: name,
	}
}

func (c *wwwService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Www.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wwwService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Www_StreamService, error) {
	req := c.c.NewRequest(c.name, "Www.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &wwwServiceStream{stream}, nil
}

type Www_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type wwwServiceStream struct {
	stream client.Stream
}

func (x *wwwServiceStream) Close() error {
	return x.stream.Close()
}

func (x *wwwServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wwwServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wwwServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wwwService) PingPong(ctx context.Context, opts ...client.CallOption) (Www_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Www.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &wwwServicePingPong{stream}, nil
}

type Www_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type wwwServicePingPong struct {
	stream client.Stream
}

func (x *wwwServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *wwwServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wwwServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wwwServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *wwwServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Www service

type WwwHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Www_StreamStream) error
	PingPong(context.Context, Www_PingPongStream) error
}

func RegisterWwwHandler(s server.Server, hdlr WwwHandler, opts ...server.HandlerOption) error {
	type www interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Www struct {
		www
	}
	h := &wwwHandler{hdlr}
	return s.Handle(s.NewHandler(&Www{h}, opts...))
}

type wwwHandler struct {
	WwwHandler
}

func (h *wwwHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WwwHandler.Call(ctx, in, out)
}

func (h *wwwHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WwwHandler.Stream(ctx, m, &wwwStreamStream{stream})
}

type Www_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type wwwStreamStream struct {
	stream server.Stream
}

func (x *wwwStreamStream) Close() error {
	return x.stream.Close()
}

func (x *wwwStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wwwStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wwwStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *wwwHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WwwHandler.PingPong(ctx, &wwwPingPongStream{stream})
}

type Www_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type wwwPingPongStream struct {
	stream server.Stream
}

func (x *wwwPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *wwwPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wwwPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wwwPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *wwwPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
