// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	"demo/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/greet/from/:name",
			Handler: greetHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/user",
			Handler: getInfoCallHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/user",
			Handler: getUserRespHandler(serverCtx),
		},
	})
}
