// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Blog service

func NewBlogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Blog service

type BlogService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Blog_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Blog_PingPongService, error)
}

type blogService struct {
	c    client.Client
	name string
}

func NewBlogService(name string, c client.Client) BlogService {
	return &blogService{
		c:    c,
		name: name,
	}
}

func (c *blogService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Blog.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Blog_StreamService, error) {
	req := c.c.NewRequest(c.name, "Blog.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &blogServiceStream{stream}, nil
}

type Blog_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type blogServiceStream struct {
	stream client.Stream
}

func (x *blogServiceStream) Close() error {
	return x.stream.Close()
}

func (x *blogServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *blogServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *blogServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *blogServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blogService) PingPong(ctx context.Context, opts ...client.CallOption) (Blog_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Blog.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &blogServicePingPong{stream}, nil
}

type Blog_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type blogServicePingPong struct {
	stream client.Stream
}

func (x *blogServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *blogServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *blogServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *blogServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *blogServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *blogServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Blog service

type BlogHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Blog_StreamStream) error
	PingPong(context.Context, Blog_PingPongStream) error
}

func RegisterBlogHandler(s server.Server, hdlr BlogHandler, opts ...server.HandlerOption) error {
	type blog interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Blog struct {
		blog
	}
	h := &blogHandler{hdlr}
	return s.Handle(s.NewHandler(&Blog{h}, opts...))
}

type blogHandler struct {
	BlogHandler
}

func (h *blogHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.BlogHandler.Call(ctx, in, out)
}

func (h *blogHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.BlogHandler.Stream(ctx, m, &blogStreamStream{stream})
}

type Blog_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type blogStreamStream struct {
	stream server.Stream
}

func (x *blogStreamStream) Close() error {
	return x.stream.Close()
}

func (x *blogStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *blogStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *blogStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *blogStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *blogHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.BlogHandler.PingPong(ctx, &blogPingPongStream{stream})
}

type Blog_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type blogPingPongStream struct {
	stream server.Stream
}

func (x *blogPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *blogPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *blogPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *blogPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *blogPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *blogPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
