// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/wow.proto

package wow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Wow service

type WowService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Wow_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Wow_PingPongService, error)
}

type wowService struct {
	c    client.Client
	name string
}

func NewWowService(name string, c client.Client) WowService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "wow"
	}
	return &wowService{
		c:    c,
		name: name,
	}
}

func (c *wowService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Wow.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wowService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Wow_StreamService, error) {
	req := c.c.NewRequest(c.name, "Wow.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &wowServiceStream{stream}, nil
}

type Wow_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type wowServiceStream struct {
	stream client.Stream
}

func (x *wowServiceStream) Close() error {
	return x.stream.Close()
}

func (x *wowServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wowServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wowServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wowService) PingPong(ctx context.Context, opts ...client.CallOption) (Wow_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Wow.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &wowServicePingPong{stream}, nil
}

type Wow_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type wowServicePingPong struct {
	stream client.Stream
}

func (x *wowServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *wowServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wowServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wowServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *wowServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Wow service

type WowHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Wow_StreamStream) error
	PingPong(context.Context, Wow_PingPongStream) error
}

func RegisterWowHandler(s server.Server, hdlr WowHandler, opts ...server.HandlerOption) error {
	type wow interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Wow struct {
		wow
	}
	h := &wowHandler{hdlr}
	return s.Handle(s.NewHandler(&Wow{h}, opts...))
}

type wowHandler struct {
	WowHandler
}

func (h *wowHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WowHandler.Call(ctx, in, out)
}

func (h *wowHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WowHandler.Stream(ctx, m, &wowStreamStream{stream})
}

type Wow_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type wowStreamStream struct {
	stream server.Stream
}

func (x *wowStreamStream) Close() error {
	return x.stream.Close()
}

func (x *wowStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wowStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wowStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *wowHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WowHandler.PingPong(ctx, &wowPingPongStream{stream})
}

type Wow_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type wowPingPongStream struct {
	stream server.Stream
}

func (x *wowPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *wowPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wowPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wowPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *wowPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
