// DO NOT EDIT, generated by goctl
package types

type Request struct {
	Name string `path:"name,options=you|me"` // 框架自动验证请求参数是否合法
}

type Response struct {
	Message string `json:"message"`
	Data    string `json:"data"`
}

type UserReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserResp struct {
	UserInfo string `json:"userinfo"`
	Code     int    `json:"code"`
	Userdata string `json:"userdata"`
}
